### PR TITLE
feat: add evie as a recommended bot

### PR DESCRIPTION
**Pull request by tristancamejo**
This pull request replaces MEE6 (an inferior bot) with Evie.

### CODE REVIEW

**Comment by GodderE2D** [comment]
I do not plan to remove MEE6 from the list of recommended bots at this moment. However, if you wish to add Evie alongside MEE6, I'm fine with that.

**Comment by toasterw** [comment]
mee6 bad ratio

**Comment by tristancamejo** [comment]
Tristan will remember that

**Comment by GodderE2D** [comment]
Re-open if necessary.

**Pull request closed without merging**
